#include "nsISupports.idl"
#include "nsIMsgFolder.idl"
#include "nsIVariant.idl"


[scriptable, uuid(0cc43330-d388-11dc-95ff-0800200c9a66)]
interface pIXMigemoMail : nsISupports
{
	nsIVariant getTermsList(
		in AString input,
		in unsigned long searchMode,
		in nsIMsgFolder folder
	);

	void loadSummaryCache(
		in nsIMsgFolder folder,
		out wstring messageIds,
		out wstring authors,
		out wstring subjects,
		out wstring recipients,
		out wstring cc,
		out wstring body
	);
	void saveSummaryCache(
		in nsIMsgFolder folder,
		in AString messageIds,
		in AString authors,
		in AString subjects,
		in AString recipients,
		in AString cc,
		in AString body
	);
	void clearSummaryCache(in nsIMsgFolder folder);
	void refreshSummaryCache(in nsIMsgFolder folder);
};
