#include "nsISupports.idl"
#include "nsIMsgFolder.idl"


[scriptable, uuid(0cc43330-d388-11dc-95ff-0800200c9a66)]
interface pIXMigemoMail : nsISupports
{
	void getTermsList(
		in AString input,
		in unsigned long searchMode,
		in nsIMsgFolder folder,
		out unsigned long count, [array, size_is(count), retval] out wstring array
	);

	void loadSummaryCache(
		in nsIMsgFolder folder,
		out wstring messageIds,
		out wstring authors,
		out wstring subjects,
		out wstring recipients,
		out wstring cc
	);
	void updateSummaryCache(
		in nsIMsgFolder folder,
		in AString messageIds,
		in AString authors,
		in AString subjects,
		in AString recipients,
		in AString cc
	);
	void clearSummaryCache(in nsIMsgFolder folder);
};
