#include "nsISupports.idl"
#include "domstubs.idl"
#include "nsIVariant.idl"
#include "nsIDOMDocument.idl"
#include "nsIDOMRange.idl"
#include "nsIDOMElement.idl"

interface nsIVariant;
interface nsIDOMDocument;
interface nsIDOMRange;
interface nsIDOMElement;


// easy API for JavaScript
[scriptable, uuid(066d0a50-bd7b-11de-8a39-0800200c9a66)]
interface xmIXMigemoAPI : nsISupports
{
	readonly attribute AString provider;

	readonly attribute AString version;
	readonly attribute AString lang;

	/* create a regular expression from roman letters.
	   returned value: RegExp object */
	nsIVariant getRegExp(
		in AString input,
		[optional] in AString flags
	);

	/* create a regular expressions from roman letters split by whitespace characters.
	   returned value: array of RegExp objects */
	nsIVariant getRegExps(
		in AString input,
		[optional] in AString flags
	);

	nsIVariant getRegExpFunctional(
		in AString input,
		[optional] in AString flags
	);
	nsIVariant getRegExpsFunctional(
		in AString input,
		[optional] in AString flags
	);
	boolean isValidFunctionalInput(in AString input);
	AString trimFunctionalInput(in AString input);
};

[scriptable, uuid(47ca4a10-bfbc-11de-8a39-0800200c9a66)]
interface xmIXMigemoQueryAPI : nsISupports
{
	AString query(in AString input);
	nsIVariant queries(in AString input);
	nsIVariant queryFunctional(in AString input);
	nsIVariant queriesFunctional(in AString input);
};

[scriptable, uuid(df8b8ec0-be06-11de-8a39-0800200c9a66)]
interface xmIXMigemoRangeFindAPI : nsISupports
{
	/* find by regular expression, and return the first item of found terms as DOM2 Range. */
	nsIDOMRange regExpFind(
		in nsIVariant regExp,
		in nsIDOMRange findRange,
		[optional] in nsIDOMRange startPoint,
		[optional] in nsIDOMRange endPoint,
		[optional] in boolean findBackwards
	);

	/* this returns all of found terms as an array. */
	nsIVariant regExpFindArray(
		in nsIVariant regExp,
		in nsIDOMRange findRange,
		[optional] in nsIDOMRange startPoint,
		[optional] in nsIDOMRange endPoint
	);
	/* for backward compatibility */
	nsIVariant regExpFindArr(
		in nsIVariant regExp,
		in nsIDOMRange findRange,
		[optional] in nsIDOMRange startPoint,
		[optional] in nsIDOMRange endPoint
	);
};

[scriptable, uuid(07db71b0-be1b-11de-8a39-0800200c9a66)]
interface xmIXMigemoHighlightAPI : nsISupports
{
	nsIVariant regExpHighlight(
		in nsIVariant regExp,
		in nsIDOMRange findRange,
		in nsIDOMElement surroundNode
	);

	nsIVariant regExpHighlightSelection(
		in nsIVariant regExp,
		in nsIDOMRange findRange,
		[optional] in nsIDOMElement surroundNode
	);

	void clearHighlight(
		in nsIDOMDocument document,
		[optional] in boolean recursively,
		[optional] in boolean selectionOnly,
		[optional] in boolean keepFoundHighlighted
	);

	void repaintHighlights(
		in nsIDOMDocument document,
		[optional] in boolean recursively,
		[optional] in boolean highlighted
	);

	/* returned values: an array of JS obejct which have following properties:
		node                : element node of the "highlight" style
		selectionController : nsISelectionController for the owner document of the highlight
	*/
	nsIVariant getHighlights(
		in nsIDOMDocument document,
		[optional] in boolean recursively
	);
};
